version: '4.0'

services:
  app:
    image: typefrenzy
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./styles:/app/styles
      - ./context:/app/context
      - ./utils:/app/utils
